#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PANMUX_REPO=$(cd -- "$SCRIPT_DIR/.." && pwd)
SOURCE_DIR=${PANMUX_SOURCE_DIR:-$PANMUX_REPO}
INSTALL_ROOT=${PANMUX_INSTALL_ROOT:-$HOME/.local/opt/panmux}
BIN_DIR=${PANMUX_BIN_DIR:-$HOME/.local/bin}
APP_DIR=${PANMUX_APP_DIR:-$HOME/.local/share/applications}
ICON_DIR=${PANMUX_ICON_DIR:-$HOME/.local/share/icons}
APP_ID=io.github.forbidden_game.panmux

find_source_ghostty_config() {
  local candidates=()
  if [[ -n "${XDG_CONFIG_HOME:-}" ]]; then
    candidates+=(
      "$XDG_CONFIG_HOME/ghostty/config.ghostty"
      "$XDG_CONFIG_HOME/ghostty/config"
    )
  fi
  candidates+=(
    "$HOME/.config/ghostty/config.ghostty"
    "$HOME/.config/ghostty/config"
  )

  local path
  for path in "${candidates[@]}"; do
    if [[ -f "$path" ]]; then
      printf '%s\n' "$path"
      return 0
    fi
  done

  return 1
}

extract_font_profile() {
  local config_path=$1
  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    /^[[:space:]]*(font-family|font-family-bold|font-family-italic|font-family-bold-italic|font-style|font-style-bold|font-style-italic|font-style-bold-italic|font-size|font-feature|font-feature-bold|font-feature-italic|font-feature-bold-italic|font-variation|font-variation-bold|font-variation-italic|font-variation-bold-italic|font-codepoint-map|window-title-font-family|adjust-cell-width|adjust-cell-height|adjust-font-baseline|adjust-underline-position|adjust-underline-thickness|adjust-strikethrough-position|adjust-strikethrough-thickness|adjust-overline-position|adjust-overline-thickness|adjust-cursor-thickness|adjust-cursor-height|adjust-box-thickness|adjust-icon-height)[[:space:]]*=/ {
      print
      found = 1
    }
    END {
      if (!found) exit 1
    }
  ' "$config_path"
}

write_panmux_font_config() {
  local config_root=$1
  local config_dir="$config_root/ghostty"
  local config_path="$config_dir/config.ghostty"
  local source_config=""
  local font_profile=""

  mkdir -p "$config_dir"

  if source_config=$(find_source_ghostty_config); then
    if font_profile=$(extract_font_profile "$source_config"); then
      :
    else
      font_profile=""
    fi
  fi

  {
    printf '# panmux bundled Ghostty config\n'
    printf '# Generated by scripts/install_local_panmux.sh\n'
    printf '# This keeps panmux on a private config profile so it does not\n'
    printf '# inherit host Ghostty font settings that may trigger fontconfig crashes.\n'
    printf '\n'

    if [[ -n "$source_config" ]]; then
      printf '# Source config: %s\n' "$source_config"
      if [[ -n "$font_profile" ]]; then
        printf '# Copied the current font-related settings into panmux defaults.\n'
      else
        printf '# No explicit font-related settings were found; panmux will use Ghostty defaults.\n'
      fi
    else
      printf '# No existing Ghostty config was found; panmux will use Ghostty defaults.\n'
    fi

    if [[ -n "$font_profile" ]]; then
      printf '\n%s\n' "$font_profile"
    fi
  } > "$config_path"
}

if [[ ! -d "$SOURCE_DIR/.git" ]]; then
  echo "error: source dir does not look like a git repo: $SOURCE_DIR" >&2
  exit 1
fi

if ! command -v zig >/dev/null 2>&1; then
  echo "error: zig not found in PATH" >&2
  exit 1
fi

revision=$(git -C "$SOURCE_DIR" rev-parse --short HEAD)
dirty=false
if [[ -n "$(git -C "$SOURCE_DIR" status --short)" ]]; then
  dirty=true
fi
if [[ "$dirty" == true ]]; then
  revision="${revision}-dirty"
fi
prefix="$INSTALL_ROOT/$revision"
current="$INSTALL_ROOT/current"
mkdir -p "$INSTALL_ROOT" "$BIN_DIR" "$APP_DIR" "$ICON_DIR"

if [[ "$dirty" == true || ! -x "$prefix/bin/ghostty" ]]; then
  echo "==> building panmux release into $prefix"
  (
    cd "$SOURCE_DIR"
    zig build -Doptimize=ReleaseFast --prefix "$prefix" install
  )
else
  echo "==> reusing existing build at $prefix"
fi

ln -sfn "$prefix" "$current"

write_panmux_font_config "$prefix/etc/xdg"

cat > "$BIN_DIR/panmux" <<EOF
#!/usr/bin/env bash
set -euo pipefail
base="\${PANMUX_HOME:-$current}"
exe="\$base/bin/ghostty"
resources="\$base/share/ghostty"
config_home="\${PANMUX_CONFIG_HOME:-\$base/etc/xdg}"
if [[ ! -x "\$exe" ]]; then
  echo "error: panmux executable not found at \$exe" >&2
  exit 1
fi
for arg in "\$@"; do
  if [[ "\$arg" == --gtk-single-instance=* ]]; then
    exec env -u NO_COLOR GHOSTTY_RESOURCES_DIR="\$resources" XDG_CONFIG_HOME="\$config_home" "\$exe" "\$@"
  fi
done
exec env -u NO_COLOR GHOSTTY_RESOURCES_DIR="\$resources" XDG_CONFIG_HOME="\$config_home" "\$exe" --gtk-single-instance=false "\$@"
EOF
chmod +x "$BIN_DIR/panmux"

cat > "$BIN_DIR/panmuxctl" <<EOF
#!/usr/bin/env bash
set -euo pipefail
base="\${PANMUX_HOME:-$current}"
exe="\$base/bin/panmuxctl"
if [[ ! -x "\$exe" ]]; then
  echo "error: panmuxctl not found at \$exe" >&2
  exit 1
fi
exec "\$exe" "\$@"
EOF
chmod +x "$BIN_DIR/panmuxctl"

cat > "$APP_DIR/panmux.desktop" <<EOF
[Desktop Entry]
Version=1.0
Name=panmux
Type=Application
Comment=Panmux terminal (Ghostty GTK fork)
TryExec=$BIN_DIR/panmux
Exec=$BIN_DIR/panmux
Icon=$APP_ID
Categories=System;TerminalEmulator;
Keywords=terminal;tty;pty;panmux;
StartupNotify=true
StartupWMClass=$APP_ID
Terminal=false
X-GNOME-UsesNotifications=true
EOF

if [[ -d "$current/share/icons" ]]; then
  mkdir -p "$ICON_DIR"
  cp -a "$current/share/icons/." "$ICON_DIR/"
fi

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APP_DIR" >/dev/null 2>&1 || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f -t "$ICON_DIR/hicolor" >/dev/null 2>&1 || true
fi

echo "==> installed panmux"
echo "source:   $SOURCE_DIR"
echo "revision: $revision"
echo "current:  $current"
echo "binary:   $BIN_DIR/panmux"
echo "ctl:      $BIN_DIR/panmuxctl"
echo "desktop:  $APP_DIR/panmux.desktop"
echo "icons:    $ICON_DIR"
echo "config:   $current/etc/xdg/ghostty/config.ghostty"
